namespace PMS
{
    partial class 员工查询
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.salarytable = new System.Windows.Forms.DataGridView();
            this.snoDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Sname = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.grosspayDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.realpayDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.paytimeDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.sALARYBindingSource1 = new System.Windows.Forms.BindingSource(this.components);
            this.pMSDataSet15 = new PMS.PMSDataSet15();
            this.textBox8 = new System.Windows.Forms.TextBox();
            this.textBox9 = new System.Windows.Forms.TextBox();
            this.textBox10 = new System.Windows.Forms.TextBox();
            this.comboBox2 = new System.Windows.Forms.ComboBox();
            this.button6 = new System.Windows.Forms.Button();
            this.label8 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.textBox12 = new System.Windows.Forms.TextBox();
            this.textBox11 = new System.Windows.Forms.TextBox();
            this.textBox5 = new System.Windows.Forms.TextBox();
            this.textBox7 = new System.Windows.Forms.TextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.button2 = new System.Windows.Forms.Button();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.withholdtable = new System.Windows.Forms.DataGridView();
            this.wITHHOLDIDDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.snoDataGridViewTextBoxColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.rIDDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.wITHHOLDTIMEDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.wITHHOLDBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.pMSDataSet12 = new PMS.PMSDataSet12();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.attendencetable = new System.Windows.Forms.DataGridView();
            this.snoDataGridViewTextBoxColumn2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.oVERTIMEDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.aBSENCEDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.aTIMEDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.aTTENDENCEBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.pMSDataSet13 = new PMS.PMSDataSet13();
            this.button3 = new System.Windows.Forms.Button();
            this.textBox4 = new System.Windows.Forms.TextBox();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.tabPage4 = new System.Windows.Forms.TabPage();
            this.textBox6 = new System.Windows.Forms.TextBox();
            this.textBox13 = new System.Windows.Forms.TextBox();
            this.stafftable = new System.Windows.Forms.DataGridView();
            this.snoDataGridViewTextBoxColumn3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.snameDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.ssexDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.sbirthDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.deptnoDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.slevelDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.stelDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.jointimeDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.sTAFFBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.pMSDataSet14 = new PMS.PMSDataSet14();
            this.textBox14 = new System.Windows.Forms.TextBox();
            this.textBox15 = new System.Windows.Forms.TextBox();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.comboBox3 = new System.Windows.Forms.ComboBox();
            this.textBox16 = new System.Windows.Forms.TextBox();
            this.textBox17 = new System.Windows.Forms.TextBox();
            this.button7 = new System.Windows.Forms.Button();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.label19 = new System.Windows.Forms.Label();
            this.label20 = new System.Windows.Forms.Label();
            this.sALARYBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.pMSDataSet11 = new PMS.PMSDataSet11();
            this.sALARYTableAdapter = new PMS.PMSDataSet11TableAdapters.SALARYTableAdapter();
            this.wITHHOLDTableAdapter = new PMS.PMSDataSet12TableAdapters.WITHHOLDTableAdapter();
            this.aTTENDENCETableAdapter = new PMS.PMSDataSet13TableAdapters.ATTENDENCETableAdapter();
            this.sTAFFTableAdapter = new PMS.PMSDataSet14TableAdapters.STAFFTableAdapter();
            this.pmsDataSet1 = new PMS.PMSDataSet();
            this.sALARYTableAdapter1 = new PMS.PMSDataSet15TableAdapters.SALARYTableAdapter();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.salarytable)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.sALARYBindingSource1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.pMSDataSet15)).BeginInit();
            this.tabPage2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.withholdtable)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.wITHHOLDBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.pMSDataSet12)).BeginInit();
            this.tabPage3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.attendencetable)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.aTTENDENCEBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.pMSDataSet13)).BeginInit();
            this.tabPage4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.stafftable)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.sTAFFBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.pMSDataSet14)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.sALARYBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.pMSDataSet11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.pmsDataSet1)).BeginInit();
            this.SuspendLayout();
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Controls.Add(this.tabPage4);
            this.tabControl1.Location = new System.Drawing.Point(19, 21);
            this.tabControl1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(1020, 679);
            this.tabControl1.TabIndex = 0;
            this.tabPage1.Controls.Add(this.salarytable);
            this.tabPage1.Controls.Add(this.textBox8);
            this.tabPage1.Controls.Add(this.textBox9);
            this.tabPage1.Controls.Add(this.textBox10);
            this.tabPage1.Controls.Add(this.comboBox2);
            this.tabPage1.Controls.Add(this.button6);
            this.tabPage1.Controls.Add(this.label8);
            this.tabPage1.Controls.Add(this.label14);
            this.tabPage1.Controls.Add(this.label17);
            this.tabPage1.Controls.Add(this.label18);
            this.tabPage1.Location = new System.Drawing.Point(4, 26);
            this.tabPage1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage1.Size = new System.Drawing.Size(1012, 649);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "工资查询";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.salarytable.AutoGenerateColumns = false;
            this.salarytable.ColumnHeadersHeightSizeMode =
                System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.salarytable.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[]
            {
                this.snoDataGridViewTextBoxColumn, this.Sname, this.grosspayDataGridViewTextBoxColumn,
                this.realpayDataGridViewTextBoxColumn, this.paytimeDataGridViewTextBoxColumn
            });
            this.salarytable.DataSource = this.sALARYBindingSource1;
            this.salarytable.Location = new System.Drawing.Point(82, 203);
            this.salarytable.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.salarytable.Name = "salarytable";
            this.salarytable.RowTemplate.Height = 23;
            this.salarytable.Size = new System.Drawing.Size(762, 404);
            this.salarytable.TabIndex = 65;
            this.snoDataGridViewTextBoxColumn.DataPropertyName = "Sno";
            this.snoDataGridViewTextBoxColumn.HeaderText = "Sno";
            this.snoDataGridViewTextBoxColumn.Name = "snoDataGridViewTextBoxColumn";
            this.Sname.DataPropertyName = "Sname";
            this.Sname.HeaderText = "Sname";
            this.Sname.Name = "Sname";
            this.grosspayDataGridViewTextBoxColumn.DataPropertyName = "Grosspay";
            this.grosspayDataGridViewTextBoxColumn.HeaderText = "Grosspay";
            this.grosspayDataGridViewTextBoxColumn.Name = "grosspayDataGridViewTextBoxColumn";
            this.realpayDataGridViewTextBoxColumn.DataPropertyName = "Realpay";
            this.realpayDataGridViewTextBoxColumn.HeaderText = "Realpay";
            this.realpayDataGridViewTextBoxColumn.Name = "realpayDataGridViewTextBoxColumn";
            this.paytimeDataGridViewTextBoxColumn.DataPropertyName = "Paytime";
            this.paytimeDataGridViewTextBoxColumn.HeaderText = "Paytime";
            this.paytimeDataGridViewTextBoxColumn.Name = "paytimeDataGridViewTextBoxColumn";
            this.sALARYBindingSource1.DataMember = "SALARY";
            this.sALARYBindingSource1.DataSource = this.pMSDataSet15;
            this.pMSDataSet15.DataSetName = "PMSDataSet15";
            this.pMSDataSet15.Namespace = "http://tempuri.org/PMSDataSet15.xsd";
            this.pMSDataSet15.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.textBox8.Location = new System.Drawing.Point(820, 42);
            this.textBox8.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox8.Name = "textBox8";
            this.textBox8.Size = new System.Drawing.Size(111, 23);
            this.textBox8.TabIndex = 64;
            this.textBox9.Location = new System.Drawing.Point(352, 40);
            this.textBox9.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox9.Name = "textBox9";
            this.textBox9.Size = new System.Drawing.Size(111, 23);
            this.textBox9.TabIndex = 62;
            this.textBox10.Location = new System.Drawing.Point(112, 40);
            this.textBox10.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox10.Name = "textBox10";
            this.textBox10.Size = new System.Drawing.Size(111, 23);
            this.textBox10.TabIndex = 61;
            this.comboBox2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBox2.FormattingEnabled = true;
            this.comboBox2.Items.AddRange(new object[] {"01", "02", "03", "04", "05", "06"});
            this.comboBox2.Location = new System.Drawing.Point(587, 42);
            this.comboBox2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.comboBox2.Name = "comboBox2";
            this.comboBox2.Size = new System.Drawing.Size(111, 25);
            this.comboBox2.TabIndex = 63;
            this.button6.Font = new System.Drawing.Font("微软雅黑", 14.25F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.button6.Location = new System.Drawing.Point(436, 116);
            this.button6.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(82, 62);
            this.button6.TabIndex = 60;
            this.button6.Text = "查询";
            this.button6.UseVisualStyleBackColor = true;
            this.button6.Click += new System.EventHandler(this.Button6_Click);
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label8.Location = new System.Drawing.Point(519, 35);
            this.label8.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(52, 27);
            this.label8.TabIndex = 59;
            this.label8.Text = "部门";
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label14.Location = new System.Drawing.Point(752, 40);
            this.label14.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(52, 27);
            this.label14.TabIndex = 58;
            this.label14.Text = "时间";
            this.label17.AutoSize = true;
            this.label17.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label17.Location = new System.Drawing.Point(273, 35);
            this.label17.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(52, 27);
            this.label17.TabIndex = 57;
            this.label17.Text = "姓名";
            this.label18.AutoSize = true;
            this.label18.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label18.Location = new System.Drawing.Point(33, 35);
            this.label18.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(52, 27);
            this.label18.TabIndex = 56;
            this.label18.Text = "工号";
            this.tabPage2.Controls.Add(this.textBox12);
            this.tabPage2.Controls.Add(this.textBox11);
            this.tabPage2.Controls.Add(this.textBox5);
            this.tabPage2.Controls.Add(this.textBox7);
            this.tabPage2.Controls.Add(this.label12);
            this.tabPage2.Controls.Add(this.button2);
            this.tabPage2.Controls.Add(this.label4);
            this.tabPage2.Controls.Add(this.label5);
            this.tabPage2.Controls.Add(this.label10);
            this.tabPage2.Controls.Add(this.withholdtable);
            this.tabPage2.Location = new System.Drawing.Point(4, 26);
            this.tabPage2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage2.Size = new System.Drawing.Size(1012, 649);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "代扣查询";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.textBox12.Location = new System.Drawing.Point(130, 44);
            this.textBox12.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox12.Name = "textBox12";
            this.textBox12.Size = new System.Drawing.Size(105, 23);
            this.textBox12.TabIndex = 77;
            this.textBox11.Location = new System.Drawing.Point(824, 45);
            this.textBox11.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox11.Name = "textBox11";
            this.textBox11.Size = new System.Drawing.Size(123, 23);
            this.textBox11.TabIndex = 75;
            this.textBox5.Location = new System.Drawing.Point(306, 45);
            this.textBox5.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox5.Name = "textBox5";
            this.textBox5.Size = new System.Drawing.Size(123, 23);
            this.textBox5.TabIndex = 73;
            this.textBox7.Location = new System.Drawing.Point(606, 45);
            this.textBox7.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox7.Name = "textBox7";
            this.textBox7.Size = new System.Drawing.Size(123, 23);
            this.textBox7.TabIndex = 72;
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label12.Location = new System.Drawing.Point(30, 40);
            this.label12.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(92, 27);
            this.label12.TabIndex = 76;
            this.label12.Text = "代扣编号";
            this.button2.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.button2.Location = new System.Drawing.Point(422, 119);
            this.button2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(83, 54);
            this.button2.TabIndex = 74;
            this.button2.Text = "查询";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new System.EventHandler(this.Button2_Click);
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label4.Location = new System.Drawing.Point(233, 40);
            this.label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(52, 27);
            this.label4.TabIndex = 71;
            this.label4.Text = "工号";
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label5.Location = new System.Drawing.Point(756, 40);
            this.label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(52, 27);
            this.label5.TabIndex = 70;
            this.label5.Text = "日期";
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label10.Location = new System.Drawing.Point(444, 40);
            this.label10.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(132, 27);
            this.label10.TabIndex = 69;
            this.label10.Text = "保险税收编号";
            this.withholdtable.AutoGenerateColumns = false;
            this.withholdtable.ColumnHeadersHeightSizeMode =
                System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.withholdtable.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[]
            {
                this.wITHHOLDIDDataGridViewTextBoxColumn, this.snoDataGridViewTextBoxColumn1,
                this.rIDDataGridViewTextBoxColumn, this.wITHHOLDTIMEDataGridViewTextBoxColumn
            });
            this.withholdtable.DataSource = this.wITHHOLDBindingSource;
            this.withholdtable.Location = new System.Drawing.Point(61, 194);
            this.withholdtable.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.withholdtable.Name = "withholdtable";
            this.withholdtable.RowTemplate.Height = 23;
            this.withholdtable.Size = new System.Drawing.Size(830, 439);
            this.withholdtable.TabIndex = 57;
            this.wITHHOLDIDDataGridViewTextBoxColumn.DataPropertyName = "WITHHOLDID";
            this.wITHHOLDIDDataGridViewTextBoxColumn.HeaderText = "WITHHOLDID";
            this.wITHHOLDIDDataGridViewTextBoxColumn.Name = "wITHHOLDIDDataGridViewTextBoxColumn";
            this.snoDataGridViewTextBoxColumn1.DataPropertyName = "Sno";
            this.snoDataGridViewTextBoxColumn1.HeaderText = "Sno";
            this.snoDataGridViewTextBoxColumn1.Name = "snoDataGridViewTextBoxColumn1";
            this.rIDDataGridViewTextBoxColumn.DataPropertyName = "RID";
            this.rIDDataGridViewTextBoxColumn.HeaderText = "RID";
            this.rIDDataGridViewTextBoxColumn.Name = "rIDDataGridViewTextBoxColumn";
            this.wITHHOLDTIMEDataGridViewTextBoxColumn.DataPropertyName = "WITHHOLDTIME";
            this.wITHHOLDTIMEDataGridViewTextBoxColumn.HeaderText = "WITHHOLDTIME";
            this.wITHHOLDTIMEDataGridViewTextBoxColumn.Name = "wITHHOLDTIMEDataGridViewTextBoxColumn";
            this.wITHHOLDBindingSource.DataMember = "WITHHOLD";
            this.wITHHOLDBindingSource.DataSource = this.pMSDataSet12;
            this.pMSDataSet12.DataSetName = "PMSDataSet12";
            this.pMSDataSet12.Namespace = "http://tempuri.org/PMSDataSet12.xsd";
            this.pMSDataSet12.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabPage3.Controls.Add(this.attendencetable);
            this.tabPage3.Controls.Add(this.button3);
            this.tabPage3.Controls.Add(this.textBox4);
            this.tabPage3.Controls.Add(this.textBox3);
            this.tabPage3.Controls.Add(this.textBox2);
            this.tabPage3.Controls.Add(this.textBox1);
            this.tabPage3.Controls.Add(this.label9);
            this.tabPage3.Controls.Add(this.label3);
            this.tabPage3.Controls.Add(this.label1);
            this.tabPage3.Controls.Add(this.label2);
            this.tabPage3.Location = new System.Drawing.Point(4, 22);
            this.tabPage3.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Size = new System.Drawing.Size(1012, 653);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "出勤查询";
            this.tabPage3.UseVisualStyleBackColor = true;
            this.attendencetable.AutoGenerateColumns = false;
            this.attendencetable.ColumnHeadersHeightSizeMode =
                System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.attendencetable.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[]
            {
                this.snoDataGridViewTextBoxColumn2, this.oVERTIMEDataGridViewTextBoxColumn,
                this.aBSENCEDataGridViewTextBoxColumn, this.aTIMEDataGridViewTextBoxColumn
            });
            this.attendencetable.DataSource = this.aTTENDENCEBindingSource;
            this.attendencetable.Location = new System.Drawing.Point(41, 181);
            this.attendencetable.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.attendencetable.Name = "attendencetable";
            this.attendencetable.RowTemplate.Height = 23;
            this.attendencetable.Size = new System.Drawing.Size(899, 333);
            this.attendencetable.TabIndex = 56;
            this.snoDataGridViewTextBoxColumn2.DataPropertyName = "Sno";
            this.snoDataGridViewTextBoxColumn2.HeaderText = "Sno";
            this.snoDataGridViewTextBoxColumn2.Name = "snoDataGridViewTextBoxColumn2";
            this.oVERTIMEDataGridViewTextBoxColumn.DataPropertyName = "OVERTIME";
            this.oVERTIMEDataGridViewTextBoxColumn.HeaderText = "OVERTIME";
            this.oVERTIMEDataGridViewTextBoxColumn.Name = "oVERTIMEDataGridViewTextBoxColumn";
            this.aBSENCEDataGridViewTextBoxColumn.DataPropertyName = "ABSENCE";
            this.aBSENCEDataGridViewTextBoxColumn.HeaderText = "ABSENCE";
            this.aBSENCEDataGridViewTextBoxColumn.Name = "aBSENCEDataGridViewTextBoxColumn";
            this.aTIMEDataGridViewTextBoxColumn.DataPropertyName = "ATIME";
            this.aTIMEDataGridViewTextBoxColumn.HeaderText = "ATIME";
            this.aTIMEDataGridViewTextBoxColumn.Name = "aTIMEDataGridViewTextBoxColumn";
            this.aTTENDENCEBindingSource.DataMember = "ATTENDENCE";
            this.aTTENDENCEBindingSource.DataSource = this.pMSDataSet13;
            this.pMSDataSet13.DataSetName = "PMSDataSet13";
            this.pMSDataSet13.Namespace = "http://tempuri.org/PMSDataSet13.xsd";
            this.pMSDataSet13.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.button3.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.button3.Location = new System.Drawing.Point(429, 102);
            this.button3.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(83, 57);
            this.button3.TabIndex = 55;
            this.button3.Text = "查询";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new System.EventHandler(this.Button3_Click);
            this.textBox4.Location = new System.Drawing.Point(831, 45);
            this.textBox4.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox4.Name = "textBox4";
            this.textBox4.Size = new System.Drawing.Size(123, 23);
            this.textBox4.TabIndex = 53;
            this.textBox3.Location = new System.Drawing.Point(93, 45);
            this.textBox3.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox3.Name = "textBox3";
            this.textBox3.Size = new System.Drawing.Size(123, 23);
            this.textBox3.TabIndex = 51;
            this.textBox2.Location = new System.Drawing.Point(618, 48);
            this.textBox2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new System.Drawing.Size(123, 23);
            this.textBox2.TabIndex = 50;
            this.textBox1.Location = new System.Drawing.Point(356, 45);
            this.textBox1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(123, 23);
            this.textBox1.TabIndex = 49;
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label9.Location = new System.Drawing.Point(21, 40);
            this.label9.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(52, 27);
            this.label9.TabIndex = 48;
            this.label9.Text = "工号";
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label3.Location = new System.Drawing.Point(763, 40);
            this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(52, 27);
            this.label3.TabIndex = 47;
            this.label3.Text = "日期";
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label1.Location = new System.Drawing.Point(499, 40);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(92, 27);
            this.label1.TabIndex = 46;
            this.label1.Text = "缺勤天数";
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label2.Location = new System.Drawing.Point(237, 40);
            this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(92, 27);
            this.label2.TabIndex = 45;
            this.label2.Text = "加班天数";
            this.tabPage4.Controls.Add(this.textBox6);
            this.tabPage4.Controls.Add(this.textBox13);
            this.tabPage4.Controls.Add(this.stafftable);
            this.tabPage4.Controls.Add(this.textBox14);
            this.tabPage4.Controls.Add(this.textBox15);
            this.tabPage4.Controls.Add(this.comboBox1);
            this.tabPage4.Controls.Add(this.comboBox3);
            this.tabPage4.Controls.Add(this.textBox16);
            this.tabPage4.Controls.Add(this.textBox17);
            this.tabPage4.Controls.Add(this.button7);
            this.tabPage4.Controls.Add(this.label6);
            this.tabPage4.Controls.Add(this.label7);
            this.tabPage4.Controls.Add(this.label11);
            this.tabPage4.Controls.Add(this.label13);
            this.tabPage4.Controls.Add(this.label15);
            this.tabPage4.Controls.Add(this.label16);
            this.tabPage4.Controls.Add(this.label19);
            this.tabPage4.Controls.Add(this.label20);
            this.tabPage4.Location = new System.Drawing.Point(4, 22);
            this.tabPage4.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Size = new System.Drawing.Size(1012, 653);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "同事查询";
            this.tabPage4.UseVisualStyleBackColor = true;
            this.textBox6.Location = new System.Drawing.Point(548, 113);
            this.textBox6.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox6.Name = "textBox6";
            this.textBox6.Size = new System.Drawing.Size(131, 23);
            this.textBox6.TabIndex = 45;
            this.textBox13.Location = new System.Drawing.Point(825, 40);
            this.textBox13.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox13.Name = "textBox13";
            this.textBox13.Size = new System.Drawing.Size(131, 23);
            this.textBox13.TabIndex = 44;
            this.stafftable.AutoGenerateColumns = false;
            this.stafftable.ColumnHeadersHeightSizeMode =
                System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.stafftable.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[]
            {
                this.snoDataGridViewTextBoxColumn3, this.snameDataGridViewTextBoxColumn,
                this.ssexDataGridViewTextBoxColumn, this.sbirthDataGridViewTextBoxColumn,
                this.deptnoDataGridViewTextBoxColumn, this.slevelDataGridViewTextBoxColumn,
                this.stelDataGridViewTextBoxColumn, this.jointimeDataGridViewTextBoxColumn
            });
            this.stafftable.DataSource = this.sTAFFBindingSource;
            this.stafftable.Location = new System.Drawing.Point(20, 276);
            this.stafftable.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.stafftable.Name = "stafftable";
            this.stafftable.RowTemplate.Height = 23;
            this.stafftable.Size = new System.Drawing.Size(987, 361);
            this.stafftable.TabIndex = 43;
            this.snoDataGridViewTextBoxColumn3.DataPropertyName = "Sno";
            this.snoDataGridViewTextBoxColumn3.HeaderText = "Sno";
            this.snoDataGridViewTextBoxColumn3.Name = "snoDataGridViewTextBoxColumn3";
            this.snameDataGridViewTextBoxColumn.DataPropertyName = "Sname";
            this.snameDataGridViewTextBoxColumn.HeaderText = "Sname";
            this.snameDataGridViewTextBoxColumn.Name = "snameDataGridViewTextBoxColumn";
            this.ssexDataGridViewTextBoxColumn.DataPropertyName = "Ssex";
            this.ssexDataGridViewTextBoxColumn.HeaderText = "Ssex";
            this.ssexDataGridViewTextBoxColumn.Name = "ssexDataGridViewTextBoxColumn";
            this.sbirthDataGridViewTextBoxColumn.DataPropertyName = "Sbirth";
            this.sbirthDataGridViewTextBoxColumn.HeaderText = "Sbirth";
            this.sbirthDataGridViewTextBoxColumn.Name = "sbirthDataGridViewTextBoxColumn";
            this.deptnoDataGridViewTextBoxColumn.DataPropertyName = "Deptno";
            this.deptnoDataGridViewTextBoxColumn.HeaderText = "Deptno";
            this.deptnoDataGridViewTextBoxColumn.Name = "deptnoDataGridViewTextBoxColumn";
            this.slevelDataGridViewTextBoxColumn.DataPropertyName = "Slevel";
            this.slevelDataGridViewTextBoxColumn.HeaderText = "Slevel";
            this.slevelDataGridViewTextBoxColumn.Name = "slevelDataGridViewTextBoxColumn";
            this.stelDataGridViewTextBoxColumn.DataPropertyName = "Stel";
            this.stelDataGridViewTextBoxColumn.HeaderText = "Stel";
            this.stelDataGridViewTextBoxColumn.Name = "stelDataGridViewTextBoxColumn";
            this.jointimeDataGridViewTextBoxColumn.DataPropertyName = "Jointime";
            this.jointimeDataGridViewTextBoxColumn.HeaderText = "Jointime";
            this.jointimeDataGridViewTextBoxColumn.Name = "jointimeDataGridViewTextBoxColumn";
            this.sTAFFBindingSource.DataMember = "STAFF";
            this.sTAFFBindingSource.DataSource = this.pMSDataSet14;
            this.pMSDataSet14.DataSetName = "PMSDataSet14";
            this.pMSDataSet14.Namespace = "http://tempuri.org/PMSDataSet14.xsd";
            this.pMSDataSet14.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.textBox14.Location = new System.Drawing.Point(825, 110);
            this.textBox14.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox14.Name = "textBox14";
            this.textBox14.Size = new System.Drawing.Size(131, 23);
            this.textBox14.TabIndex = 42;
            this.textBox15.Location = new System.Drawing.Point(323, 110);
            this.textBox15.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox15.Name = "textBox15";
            this.textBox15.Size = new System.Drawing.Size(131, 23);
            this.textBox15.TabIndex = 41;
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {"01", "02", "03", "04", "05", "06"});
            this.comboBox1.Location = new System.Drawing.Point(96, 112);
            this.comboBox1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(131, 25);
            this.comboBox1.TabIndex = 40;
            this.comboBox3.FormattingEnabled = true;
            this.comboBox3.Items.AddRange(new object[] {"男", "女"});
            this.comboBox3.Location = new System.Drawing.Point(548, 41);
            this.comboBox3.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.comboBox3.Name = "comboBox3";
            this.comboBox3.Size = new System.Drawing.Size(122, 25);
            this.comboBox3.TabIndex = 39;
            this.textBox16.Location = new System.Drawing.Point(323, 35);
            this.textBox16.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox16.Name = "textBox16";
            this.textBox16.Size = new System.Drawing.Size(131, 23);
            this.textBox16.TabIndex = 38;
            this.textBox17.Location = new System.Drawing.Point(96, 35);
            this.textBox17.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textBox17.Name = "textBox17";
            this.textBox17.Size = new System.Drawing.Size(131, 23);
            this.textBox17.TabIndex = 37;
            this.button7.Font = new System.Drawing.Font("微软雅黑", 14.25F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.button7.Location = new System.Drawing.Point(427, 186);
            this.button7.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(102, 62);
            this.button7.TabIndex = 33;
            this.button7.Text = "查询";
            this.button7.UseVisualStyleBackColor = true;
            this.button7.Click += new System.EventHandler(this.Button7_Click);
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label6.Location = new System.Drawing.Point(28, 103);
            this.label6.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(52, 27);
            this.label6.TabIndex = 32;
            this.label6.Text = "部门";
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label7.Location = new System.Drawing.Point(255, 102);
            this.label7.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(52, 27);
            this.label7.TabIndex = 31;
            this.label7.Text = "级别";
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label11.Location = new System.Drawing.Point(700, 102);
            this.label11.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(92, 27);
            this.label11.TabIndex = 30;
            this.label11.Text = "联系方式";
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label13.Location = new System.Drawing.Point(481, 102);
            this.label13.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(52, 27);
            this.label13.TabIndex = 29;
            this.label13.Text = "时间";
            this.label15.AutoSize = true;
            this.label15.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label15.Location = new System.Drawing.Point(481, 31);
            this.label15.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(52, 27);
            this.label15.TabIndex = 28;
            this.label15.Text = "性别";
            this.label16.AutoSize = true;
            this.label16.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label16.Location = new System.Drawing.Point(700, 35);
            this.label16.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(92, 27);
            this.label16.TabIndex = 27;
            this.label16.Text = "出生日期";
            this.label19.AutoSize = true;
            this.label19.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label19.Location = new System.Drawing.Point(255, 31);
            this.label19.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(52, 27);
            this.label19.TabIndex = 26;
            this.label19.Text = "姓名";
            this.label20.AutoSize = true;
            this.label20.Font = new System.Drawing.Font("微软雅黑", 15F, System.Drawing.FontStyle.Bold,
                System.Drawing.GraphicsUnit.Point, ((byte) (134)));
            this.label20.Location = new System.Drawing.Point(28, 31);
            this.label20.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(52, 27);
            this.label20.TabIndex = 25;
            this.label20.Text = "工号";
            this.sALARYBindingSource.DataMember = "SALARY";
            this.sALARYBindingSource.DataSource = this.pMSDataSet11;
            this.pMSDataSet11.DataSetName = "PMSDataSet11";
            this.pMSDataSet11.Namespace = "http://tempuri.org/PMSDataSet11.xsd";
            this.pMSDataSet11.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.sALARYTableAdapter.ClearBeforeFill = true;
            this.wITHHOLDTableAdapter.ClearBeforeFill = true;
            this.aTTENDENCETableAdapter.ClearBeforeFill = true;
            this.sTAFFTableAdapter.ClearBeforeFill = true;
            this.pmsDataSet1.DataSetName = "PMSDataSet";
            this.pmsDataSet1.Namespace = "http://tempuri.org/PMSDataSet.xsd";
            this.pmsDataSet1.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.sALARYTableAdapter1.ClearBeforeFill = true;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1044, 684);
            this.Controls.Add(this.tabControl1);
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "员工查询";
            this.Text = "员工查询";
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize) (this.salarytable)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.sALARYBindingSource1)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.pMSDataSet15)).EndInit();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize) (this.withholdtable)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.wITHHOLDBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.pMSDataSet12)).EndInit();
            this.tabPage3.ResumeLayout(false);
            this.tabPage3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize) (this.attendencetable)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.aTTENDENCEBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.pMSDataSet13)).EndInit();
            this.tabPage4.ResumeLayout(false);
            this.tabPage4.PerformLayout();
            ((System.ComponentModel.ISupportInitialize) (this.stafftable)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.sTAFFBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.pMSDataSet14)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.sALARYBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.pMSDataSet11)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.pmsDataSet1)).EndInit();
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.TabPage tabPage4;
        private PMS.PMSDataSet11 pMSDataSet11;
        private System.Windows.Forms.BindingSource sALARYBindingSource;
        private PMS.PMSDataSet11TableAdapters.SALARYTableAdapter sALARYTableAdapter;
        private System.Windows.Forms.DataGridView salarytable;
        private System.Windows.Forms.TextBox textBox8;
        private System.Windows.Forms.TextBox textBox9;
        private System.Windows.Forms.TextBox textBox10;
        private System.Windows.Forms.ComboBox comboBox2;
        private System.Windows.Forms.Button button6;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.TextBox textBox12;
        private System.Windows.Forms.TextBox textBox11;
        private System.Windows.Forms.TextBox textBox5;
        private System.Windows.Forms.TextBox textBox7;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.DataGridView withholdtable;
        private PMS.PMSDataSet12 pMSDataSet12;
        private System.Windows.Forms.BindingSource wITHHOLDBindingSource;
        private PMS.PMSDataSet12TableAdapters.WITHHOLDTableAdapter wITHHOLDTableAdapter;
        private System.Windows.Forms.DataGridViewTextBoxColumn wITHHOLDIDDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn snoDataGridViewTextBoxColumn1;
        private System.Windows.Forms.DataGridViewTextBoxColumn rIDDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn wITHHOLDTIMEDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridView attendencetable;
        private System.Windows.Forms.Button button3;
        private System.Windows.Forms.TextBox textBox4;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private PMS.PMSDataSet13 pMSDataSet13;
        private System.Windows.Forms.BindingSource aTTENDENCEBindingSource;
        private PMS.PMSDataSet13TableAdapters.ATTENDENCETableAdapter aTTENDENCETableAdapter;
        private System.Windows.Forms.DataGridViewTextBoxColumn snoDataGridViewTextBoxColumn2;
        private System.Windows.Forms.DataGridViewTextBoxColumn oVERTIMEDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn aBSENCEDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn aTIMEDataGridViewTextBoxColumn;
        private System.Windows.Forms.TextBox textBox6;
        private System.Windows.Forms.TextBox textBox13;
        private System.Windows.Forms.DataGridView stafftable;
        private System.Windows.Forms.TextBox textBox14;
        private System.Windows.Forms.TextBox textBox15;
        private System.Windows.Forms.ComboBox comboBox1;
        private System.Windows.Forms.ComboBox comboBox3;
        private System.Windows.Forms.TextBox textBox16;
        private System.Windows.Forms.TextBox textBox17;
        private System.Windows.Forms.Button button7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label20;
        private PMS.PMSDataSet14 pMSDataSet14;
        private System.Windows.Forms.BindingSource sTAFFBindingSource;
        private PMS.PMSDataSet14TableAdapters.STAFFTableAdapter sTAFFTableAdapter;
        private System.Windows.Forms.DataGridViewTextBoxColumn snoDataGridViewTextBoxColumn3;
        private System.Windows.Forms.DataGridViewTextBoxColumn snameDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn ssexDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn sbirthDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn deptnoDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn slevelDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn stelDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn jointimeDataGridViewTextBoxColumn;
        private PMS.PMSDataSet pmsDataSet1;
        private PMS.PMSDataSet15 pMSDataSet15;
        private System.Windows.Forms.BindingSource sALARYBindingSource1;
        private PMS.PMSDataSet15TableAdapters.SALARYTableAdapter sALARYTableAdapter1;
        private System.Windows.Forms.DataGridViewTextBoxColumn snoDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn Sname;
        private System.Windows.Forms.DataGridViewTextBoxColumn grosspayDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn realpayDataGridViewTextBoxColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn paytimeDataGridViewTextBoxColumn;
    }
}